django_lifecycle/__init__.py, tests/testapp/migrations/0001_initial.py, tests/testapp/models.py
This is a bug we have encountered a couple of times. Using Django v2, we have made our `User` model be a `LifecycleModelMixin`, and have various other models that create ManyToManyFields against `User`.
This breaks when we create a new `User`, and the `LifecycleModelMixin` calls the `before_create` hooks. `_potentially_hooked_methods()` doesn't recognise the auto-magically created reverse field of the many-to-many relationship as a Django field, so it tries to get the attribute in order to see if it is a callable marked as a lifecycle hook. However, getting the attribute fails because the reverse many-to-many lookup requires the primary key of the `User` instance, but said primary key does not exist because the instance hasn't been saved yet
I note that there was a brief comment on a …
=> Many to many bug

tests/testapp/tests/test_mixin.py
In the project's code instances of `NotSet` class never used - only class object itself. Because of this in the tests also should be used only class objects and not it's instances.
=> Improve tests

README.md, tox.ini
This change is needed because of using `is_cached` attribute of `field`
in `_clear_watched_fk_model_cache` method of `LifecycleModelMixin`. This
attribute was added to `ForeignKey` object only in Django 2.0.
Refs: https://github.com/django/django/pull/6721/files#diff-3010fc5a498b7171c342520f34507968R82
* Removed testing on Django versions before 2.0.
* Added testing on Python 3.7. Removed testing on Python 3.4.
* Added testing on Django 2.0, Django 2.1, Django 2.2.
Refs: #23
=> Revise `tox.ini`

docs/index.md
I found this really neat library, and was excitedly reading the docs when I ran across a broken link. The 'Read on' link in the index.md file was linking to `/examples/`, when it apparently should have been linking to `examples.md`, based on how pages are linked to each other elsewhere in the docs. So I fixed that.
=> Fixed 'Read on' link in Introduction docs

README.md, django_lifecycle/__init__.py, django_lifecycle/decorators.py, django_lifecycle/hooks.py
Static typed variables will be easy to use. No breaking changes, previous method also works.  
```python
from django_lifecycle import LifecycleModel, hook, BEFORE_UPDATE, AFTER_UPDATE
@hook(AFTER_UPDATE, when="status", was="draft", is_now="published")
def method_action():
pass
```
------------------------------ vs ------------------------------
```python3
from django_lifecycle import LifecycleModel, hook
@hook('after_update', when="status", was="draft", is_now="published")
def method_action():
pass
```
=> Added hooks names as variable for easy import and use

README.md, requirements.txt, setup.py, tox.ini
Library is already supporting py3.8 and Django3.0, so no changes needed.
Support has been added to test matrix for tox and to readme. #45
=> Added support for Python 3.8 and Django 3.0 #45

django_lifecycle/mixins.py, docs/examples.md, docs/fk_changes.md, docs/hooks_and_conditions.md, docs/index.md
#41 adds constants for hook names, but these constants were not used in docs and in the implementation.
This PR changes all occurrences of hardcoded hook names to their constant representation - in docs and also in implementation in `LifecycleModelMixin`.
=> Use constants for hook names

django_lifecycle/__init__.py, django_lifecycle/decorators.py, django_lifecycle/django_info.py, django_lifecycle/mixins.py, django_lifecycle/utils.py, tests/testapp/models.py, tests/testapp/tests/test_decorator.py, tests/testapp/tests/test_mixin.py, tests/testapp/tests/test_user_account.py
Utility function `_get_model_property_names` is currently used for getting attribute names of properties to avoid potential side-effects during getting them. This workaround is great, but it isn't covering all possible properties types (e.g. `functools.cached_property`), only builtin `property` and `cached_property` from Django.
Since `_potentially_hooked_methods` use `cached_property`, the results are cached on an instance, not on class -- but in my opinion, it's useless to have them valid for instance. Except for edge cases (dynamic definition of a method with hook during runtime) are the hooked methods the same for all instances of one model class. Because of that, `_potentially_hooked_methods` is evaluated 1000 times in this code:
```python
[ModelInheritedFromLifecycleMixin() for _ in …
```
=> Feature: hooked methods cached on class

django_lifecycle/utils.py
The `GenericForeignKey` field does not provide a `get_internal_type`
method so when checking if it's a ForeignKey or not an AttributeError is
raised.
This adjusts the code to ignore this `AttributeError` which effectively
un-monitors the `GenericForeignKey` itself. However, it does leave the
underlying `ForeignKey` to the `ContentType` table and the primary key
storage field indexing into that table monitored. This does not enable
support for hooking on the name of the `GenericForeignKey`, but hooking
on the underlying fields that support that `GenericForeignKey` should
still be possible.
closes #42
=> Skip GenericForeignKey fields

django_lifecycle/mixins.py
Hooks on OneToOneFields are not triggered due to missing "_id" suffix. This change extends get_field_names and sanitize_field_name functions to handle OneToOneFields along with ForeignKeys.
=> Handle OneToOneFields

django_lifecycle/django_info.py, tests/settings.py
distutils is [deprecated in python 3.10+](https://www.python.org/dev/peps/pep-0632/) and will be removed in 3.12.
This replaces the current distutils based version checking with packaging and fixes deprecation warnings like:
```
.../.venv/lib/python3.10/site-packages/django_lifecycle/django_info.py:7: DeprecationWarning: distutils Ver
sion classes are deprecated. Use packaging.version instead.
if StrictVersion(django.__version__) < StrictVersion("1.9"):
```
=> Switching from distutils to packaging.version for version checking

django_lifecycle/decorators.py, django_lifecycle/mixins.py, docs/examples.md, docs/hooks_and_conditions.md, requirements.txt, tests/testapp/models.py, tests/testapp/tests/test_mixin.py, tests/testapp/tests/test_user_account.py
This is my attempt to address #97. 
```python
@hook(AFTER_CREATE, on_commit=True)
def do_after_create_jobs(self):
enqueue_job(send_item_shipped_notication, self.item_id)
```
Instead of adding a new hook or new global configuration I ended up settling on what amounts to a nice way to use [django.db.transaction.on_commit](https://docs.djangoproject.com/en/3.2/topics/db/transactions/#django.db.transaction.on_commit) with `django-lifecycle` hooks.
The only thing in here that might be a little odd is that I needed to use `functools.partial` to make sure the model instance stayed in scope to actually execute during the `on_commit` callback.
Happy to make any small adjustments you might want, or if you don't think this is the right approach I can just keep using the version I've vendored in to …
=> Add optional `@hook` `on_commit` argument to for executing hooks `on_commit`

django_lifecycle/mixins.py, tests/testapp/tests/test_mixin.py
@AbdullahKady thanks for your recent PR and introducing this concept. 
I realized that some condition checks (is_now, is_not, was, was_not) do not seem to depend on whether the field in question has been synced to the database. This PR tries to account for that. 
Does this seem correct to you? If you have time, I'd appreciate a code review.
=> Only check if fields actually updated for certain condition checks

django_lifecycle/dataclass_validation.py, django_lifecycle/decorators.py, django_lifecycle/mixins.py, tests/testapp/tests/test_mixin.py
Maybe it's a bit unnecessary, but I think that by converting the decorator into a class it will be easier to extend the functionality and keep it simpler. Also, we gain autocompletion on our IDEs.
Also, I've separated each validation in it's own method
=> refactor decorator into a dataclass

django_lifecycle/mixins.py, tests/testapp/models.py, tests/testapp/tests/test_mixin.py, tests/testapp/tests/test_user_account.py
After saving an instance, reset the `_initial_state` using a `on_commit` callback. This makes the `has_changed` and `initial_value` API work with hooks that run with `on_commit=True`.
Fixes #117
=> Reset initial state using a on_commit transaction

README.md, django_lifecycle/__init__.py, requirements.txt, setup.py, tests/settings.py, tests/testapp/tests/test_user_account.py, tox.ini
fixed #114
adopted some of the changes in #115
and those in https://github.com/rsinger86/django-lifecycle/compare/0.9.2...0.9.3
After this is merged, the next PR i will likely make is to drop support for Django versions that are outdated. This will be everything before 3.2 and 4.0.
=> 🚧chore: Add support for Django 4.2

django_lifecycle/mixins.py, docs/advanced.md, tests/testapp/tests/test_mixin.py
=> Update the initial state after calling `refresh_from_db` on the model instance

django_lifecycle/mixins.py, django_lifecycle/model_state.py, django_lifecycle/utils.py
This is a first step into remove most of the methods present in LifecycleMixin. Those methods end up being in lifecycle users models, where, in my opinion, they don't belong.
I've left those methods for backwards compatibility, but they will be removed in the future
=> Extract model state methods

docs/advanced.md
Update the documented return type hint for initial_value() from bool to typing.Any
to accurately reflect that it returns the field's original value of any type.
Fix #165
=> docs: Update return type hint in utility methods documentation

setup.py
This should allow type-checkers like Mypy to run against this package.
Resolves #167.
=> Declare package to be fully typed
